import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Introduction from "../components/Introduction";
import Detail from "../components/Detail";
import Testimonial from "../components/Testimonial";
import { useState } from "react";
import Arrow from "../svg/icon-arrow-down.svg";
import Facebook from "../svg/icon-facebook.svg";
import Instagram from "../svg/icon-instagram.svg";
import Pinterest from "../svg/icon-pinterest.svg";
import Twitter from "../svg/icon-twitter.svg";
import Hamburger from "../svg/icon-hamburger.svg";
import Logo from "../svg/logo.svg";
export default function Home() {
    const [open, setOpen] = useState(false);
    return (
        <div className={styles.main_wrap}>
            <Head>
                <title>Frontend Mentor | Sunnyside agency landing page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>
            <header className={styles.header}>
                <div className={styles.navigation_wrap}>
                    <Logo />

                    <button
                        type="button"
                        aria-label="menu"
                        className={styles.hamburger_btn}
                        onClick={() => setOpen(!open)}
                    >
                        <Hamburger />
                    </button>

                    <div
                        className={`${styles.menu} ${
                            open ? styles.menu_mobile : null
                        } `}
                    >
                        <div className={open ? styles.triangle : null}></div>
                        <a href="#">About</a>
                        <a href="#">Services</a>
                        <a href="#">Projects</a>
                        <button
                            type="button"
                            aria-label="button"
                            className={styles.menu_btn}
                        >
                            CONTACT
                        </button>
                    </div>
                </div>
                <div className={styles.introduction}>
                    <h1>WE ARE CREATIVES</h1>

                    <div className={styles.arrow}>
                        <Arrow />
                    </div>
                </div>
            </header>
            <main className={styles.main}>
                <Introduction
                    order="order"
                    image={
                        <picture>
                            <source
                                srcSet="/images/desktop/image-transform.jpg"
                                media="(min-width:750px)"
                            />
                            <img
                                src="/images/mobile/image-transform.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Transform your brand"
                    paragraph="
                                We are a full-service creative agency
                                specializing in helping brands grow fast. Engage
                                your clients through compelling visuals that do
                                most of the marketing for you."
                    color="yellow"
                />

                <Introduction
                    image={
                        <picture>
                            <source
                                srcSet="/images/desktop/image-stand-out.jpg"
                                media="(min-width:750px)"
                            />
                            <img
                                src="/images/mobile/image-stand-out.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Stand out to the right audience"
                    paragraph="Using a collaborative formula of designers,
                                researchers, photographers, videographers, and
                                copywriters, we’ll build and extend your brand
                                in digital places."
                    color="red"
                />
            </main>
            <section
                className={styles.section_details}
                aria-label="more details"
            >
                <Detail
                    image={
                        <picture>
                            <source
                                srcSet="  /images/desktop/image-graphic-design.jpg"
                                media="(min-width:750px)"
                            />
                            <img
                                src="/images/mobile/image-graphic-design.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Graphic Design"
                    paragraph="
                            Great design makes you memorable. We deliver artwork
                            that underscores your brand message and captures
                            potential clients’ attention."
                    color="green"
                />

                <Detail
                    image={
                        <picture>
                            <source
                                srcSet="  /images/desktop/image-photography.jpg"
                                media="(min-width:750px)"
                            />
                            <img
                                src="/images/mobile/image-photography.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Photography"
                    paragraph="
                            Increase your credibility by getting the most
                            stunning, high-quality photos that improve your
                            business image.
                        "
                    color="blue"
                />
            </section>

            <section
                className={styles.section_testimonials}
                aria-label="testimonials"
            >
                <h4> CLIENT TESTIMONIALS</h4>
                <div className={styles.testimonial_container}>
                    <Testimonial
                        picture={<img src="/images/image-emily.jpg" alt="" />}
                        info="We put our trust in Sunnyside and they delivered,
                         making sure our needs were met and deadlines were
                            always hit."
                        name="Emily R."
                        job="Marketing Director"
                    />

                    <Testimonial
                        picture={<img src="/images/image-thomas.jpg" alt="" />}
                        info="Sunnyside’s enthusiasm coupled with their keen interest in our brand’s success made it a satisfying and enjoyable experience."
                        name="  Thomas S."
                        job=" Chief Operating Officer"
                    />

                    <Testimonial
                        picture={<img src="/images/image-jennie.jpg" alt="" />}
                        info="Incredible end result! Our sales increased over 400% when we worked with Sunnyside. Highly recommended!"
                        name="  Jennie F."
                        job=" Business Owner"
                    />
                </div>
            </section>
            <section
                className={styles.image_container}
                aria-label="more images"
            >
                <picture>
                    <source
                        srcSet=" images/desktop/image-gallery-milkbottles.jpg"
                        media="(min-width:750px)"
                    />
                    <img
                        src="images/mobile/image-gallery-milkbottles.jpg"
                        alt=""
                    />
                </picture>
                <picture>
                    <source
                        srcSet=" images/desktop/image-gallery-orange.jpg"
                        media="(min-width:750px)"
                    />

                    <img src="images/mobile/image-gallery-orange.jpg" alt="" />
                </picture>

                <picture>
                    <source
                        srcSet=" images/desktop/image-gallery-cone.jpg"
                        media="(min-width:750px)"
                    />
                    <img src="images/mobile/image-gallery-cone.jpg" alt="" />
                </picture>
                <picture>
                    <source
                        srcSet=" images/desktop/image-gallery-sugarcubes.jpg"
                        media="(min-width:750px)"
                    />
                    <img
                        src="images/mobile/image-gallery-sugar-cubes.jpg"
                        alt=""
                    />
                </picture>
            </section>
            <footer className={styles.footer}>
                <div className={styles.footer_container}>
                    <Logo />

                    <div className={styles.link_wrap}>
                        <a href="#">About </a>
                        <a href="#">Services</a>
                        <a href="#">Projects</a>
                    </div>
                    <div className={styles.social}>
                        <a href="#" aria-label="facebook">
                            <Facebook />
                        </a>
                        <a href="#" aria-label="instagram">
                            <Instagram />
                        </a>
                        <a href="#" aria-label="twitter">
                            <Twitter />
                        </a>
                        <a href="#" aria-label="pinterest">
                            <Pinterest />
                        </a>
                    </div>
                </div>
            </footer>
        </div>
    );
}
